### ISSUE TITLE
Notice to inform Rails 4.2.x devs that rack-zippy isn't likely needed

### ISSUE THREAD

**Issue by eliotsykes** [eliotsykes/rack-zippy#39]
Add notice to tell Rails 4.2.x developers that rack-zippy won't be needed for their app as Rails 4.2.x looks like its going to include gzip-serving abilities. See Rails 4.2.x release notes

**Comment by eliotsykes** [comment]
Consider outputting warning notice to console if `Rails.version >= 4.2` is detected.

**Comment by likethesky** [comment]
*Is* this the case on Rails 4.2.1?  I don't see `Vary: Accept-Encoding` nor `Content-Encoding: gzip` on my Rails 4.2.1 app running on Heroku. I do have `config.server_static_files = true` in my production.rb, btw.

Also, I'm hoping to gzip the REST endpoints I serve via Rails in my app as well--I think I still need to use Rack Deflater to achieve that on Heroku--regardless of whether I'm running rack-zippy or using Rails 4.2.1--is that your advice as well? Thanks.

**Comment by nateberkopec** [comment]
Here's the PR: https://github.com/rails/rails/pull/16466

Worth noting that Sprockets 3.0 does not gzip assets anymore, so I'm not sure what we're supposed to do :(

**Comment by eliotsykes** [comment]
Yep, stay away from sprockets 3.0 if you want your asset files gzipped at precompile time. Downgrade/fix the version in your `Gemfile`. More advice here: https://github.com/rails/sprockets/issues/26

**Comment by eliotsykes** [comment]
@likethesky What version of sprockets do you have in the `Gemfile` for that app?

**Comment by eliotsykes** [comment]
Closed by #47
