### ISSUE TITLE
Introduce config option for file extensions to treat as static files

### ISSUE THREAD

**Issue by eliotsykes** [eliotsykes/rack-zippy#4]
The STATIC_EXTENSION_REGEX is responsible for deciding what requests rack-zippy will treat as static files.

STATIC_EXTENSION_REGEX = /\.(?:css|js|html|htm|txt|ico|png|jpg|jpeg|gif|pdf|svg|zip|gz|eps|psd|ai)\z/i

At time of writing, there are only two forks of the original rack-zippy repo (see links to diffs below) and the only modification they make is to the value of STATIC_EXTENSION_REGEX.

From @mhodgson / @GoBoundless, "Don't consider html, htm, pdf, or txt as static":
https://github.com/GoBoundless/rack-zippy/commit/2ff888ffaa7f0987dcf57239a6a872aa3cff09a2

And from @Ahmedrali, "Add 'xap' to the available extension"
https://github.com/Ahmedrali/rack-zippy/commit/f58b0f0e8741cbb303af29a88232c42e0ce65eb4

I'd like to introduce a config option to help out devs who may want to make a similar customisation in the future, and so avoid forking.

One idea is to expose STATIC_EXTENSION_REGEX as a config option, and make the current regex the default option, leaving developers free to override the option within their own apps.

Another consideration is whether this needs to be a regex at all, perhaps we'd be better served by making the option an array of extensions that can be modified or replaced. Mmm, yes, that sounds tastier right now. Named something like Rack::Zippy::AssetServer.config.static_file_extensions perhaps.  I'll take some time to reflect. 

Any devs with an interest in this, please add your own thoughts below.

**Comment by eliotsykes** [comment]
Potential PR for this #45

**Comment by eliotsykes** [comment]
Fixed in rack-zippy 3.0.0. See README for configuration. **Important!** Monkey patches to the regex will not work in version 3+, the regex constant has been removed.

**Comment by supermomonga** [comment]
:+1:
