### ISSUE TITLE
Answering with 404 on invalid path

### ISSUE THREAD

**Issue by Plaristote** [eliotsykes/rack-zippy#44]
Greetings !

I have an issue on my application: some user probably fucked up a link and ended up making a link which looks like this: "www.mysite.com/s...y_Gaia".

This is an invalid path to rack-zippy, and it throws a SecurityError. It cuts the connection (triggering warnings on our logger) and doesn't redirect the user to the view that he should expect (the 404 page).

Any idea how I could fix this, knowing that I'm running Rails 3 ?
Also, shouldn't the middleware give a chance to the Rails application to handle such paths ?

**Comment by eliotsykes** [comment]
Hi @Plaristote - try upgrading rack-zippy to version `~> 2.0.2` as that `SecurityError` behaviour has been replaced to return `404 Not Found` instead.

**Comment by Plaristote** [comment]
Thanks !
