### ISSUE TITLE
Wrong number of argument 

### ISSUE THREAD

**Issue by Hadaria** [eliotsykes/rack-zippy#50]
I actually got the following error when i'm trying to launch my rails app : ArgumentError: wrong number of arguments (1 for 2) (line 21)

Didn't touched any files of rack-zippy, it's just poped out of nowhere.

Ruby version : 2.0.0
Rails version : 4.2.0

**Comment by eliotsykes** [comment]
Hi @Hadaria , thanks for reporting. With versions of Rails >= 4.2.0 you can remove rack-zippy, Rails >= 4.2 takes care of serving .gz files.
